name = "shimarisu-site"
pages_build_output_dir = "public"
compatibility_date = "2026-05-12"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAAFKKgJEkbiLmW0vr"
KAITORI_ORIGIN = "https://shimarisu-fudosan.com"

[env.preview.vars]
TURNSTILE_SITE_KEY = "0x4AAAAAAFKKgjIjftTk4ezU"
KAITORI_ORIGIN = "https://work-notes.shimarisu-site.pages.dev"
